# Generated by Django 6.0.5 on 2026-06-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingOcrDocument",
            fields=[
                (
                    "meeting_ocr_document_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="OCR 문서 식별번호",
                    ),
                ),
                ("document_id", models.IntegerField(verbose_name="내부문서 식별번호")),
                (
                    "kind",
                    models.CharField(
                        choices=[("agenda", "기초 안건"), ("prep", "회의 준비 자료")],
                        max_length=20,
                        verbose_name="용도",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        db_column="meeting_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.meeting",
                        verbose_name="회의",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_ocr_document",
            },
        ),
    ]
