# Generated by Django 6.0.6 on 2026-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='abc123', max_length=255, verbose_name='비밀번호'),
        ),
    ]
